import dotenv from 'dotenv';
import mongoose, { Schema, model } from 'mongoose';

dotenv.config();

export interface PlaceSeed {
  placeId: string;
  name: string;
  district: string;
  category: string;
  lat: number;
  lng: number;
  description: string;
  estimatedCost: number;
  createdAt: Date;
  updatedAt: Date;
}

const baseDate = new Date('2026-05-24T05:07:40.005Z');

const placeSchema = new Schema<PlaceSeed>(
  {
    placeId: { type: String, required: true, unique: true },
    name: { type: String, required: true },
    district: { type: String, required: true },
    category: { type: String, required: true },
    lat: { type: Number, required: true },
    lng: { type: Number, required: true },
    description: { type: String, required: true },
    estimatedCost: { type: Number, required: true },
    createdAt: { type: Date, required: true },
    updatedAt: { type: Date, required: true },
  },
  { collection: 'places' }
);

const Place = mongoose.models.Place || model<PlaceSeed>('Place', placeSchema);

export const places: PlaceSeed[] = [
  {
    placeId: 'galle-face-green',
    name: 'Galle Face Green',
    district: 'Colombo',
    category: 'Scenic Views',
    lat: 6.9271,
    lng: 79.8426,
    description: 'Oceanfront promenade popular for sunsets and street food.',
    estimatedCost: 500,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'gangaramaya-temple',
    name: 'Gangaramaya Temple',
    district: 'Colombo',
    category: 'Religious Sites',
    lat: 6.9147,
    lng: 79.8568,
    description: 'Buddhist temple blending modern architecture and sacred art.',
    estimatedCost: 1500,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'independence-memorial-hall',
    name: 'Independence Memorial Hall',
    district: 'Colombo',
    category: 'Historical Sites',
    lat: 6.9035,
    lng: 79.8696,
    description: 'National monument commemorating Sri Lanka independence.',
    estimatedCost: 300,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'colombo-national-museum',
    name: 'National Museum Colombo',
    district: 'Colombo',
    category: 'Cultural Experiences',
    lat: 6.9106,
    lng: 79.8612,
    description: 'Largest museum in the country with royal artifacts.',
    estimatedCost: 2000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'viharamahadevi-park',
    name: 'Viharamahadevi Park',
    district: 'Colombo',
    category: 'Nature',
    lat: 6.9173,
    lng: 79.8649,
    description: 'Central city park with shaded paths and open lawns.',
    estimatedCost: 400,
    createdAt: baseDate,
    updatedAt: baseDate,
  },

  {
    placeId: 'negombo-beach',
    name: 'Negombo Beach',
    district: 'Gampaha',
    category: 'Beaches',
    lat: 7.2083,
    lng: 79.8358,
    description: 'Golden sands, fishing boats, and lively seaside cafes.',
    estimatedCost: 1000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'negombo-dutch-fort',
    name: 'Dutch Fort Negombo',
    district: 'Gampaha',
    category: 'Historical Sites',
    lat: 7.2049,
    lng: 79.8301,
    description: 'Seventeenth-century fort ruins by the lagoon.',
    estimatedCost: 600,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'angurukaramulla-temple',
    name: 'Angurukaramulla Temple',
    district: 'Gampaha',
    category: 'Religious Sites',
    lat: 7.2076,
    lng: 79.8616,
    description: 'Temple known for its giant Buddha statue and murals.',
    estimatedCost: 700,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'muthurajawela-wetland',
    name: 'Muthurajawela Wetland',
    district: 'Gampaha',
    category: 'Wildlife',
    lat: 7.0339,
    lng: 79.8678,
    description: 'Wetland sanctuary with boat tours and birdlife.',
    estimatedCost: 2500,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'hamilton-canal',
    name: 'Hamilton Canal',
    district: 'Gampaha',
    category: 'Scenic Views',
    lat: 7.1652,
    lng: 79.8583,
    description: 'Historic canal lined with palms and fishing villages.',
    estimatedCost: 500,
    createdAt: baseDate,
    updatedAt: baseDate,
  },

  {
    placeId: 'kalutara-bodhiya',
    name: 'Kalutara Bodhiya',
    district: 'Kalutara',
    category: 'Religious Sites',
    lat: 6.5833,
    lng: 79.9597,
    description: 'Sacred Bodhi tree and stupa on the riverbank.',
    estimatedCost: 800,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'richmond-castle',
    name: 'Richmond Castle',
    district: 'Kalutara',
    category: 'Historical Sites',
    lat: 6.6048,
    lng: 79.9792,
    description: 'Edwardian mansion with landscaped gardens.',
    estimatedCost: 1500,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'bentota-beach',
    name: 'Bentota Beach',
    district: 'Kalutara',
    category: 'Beaches',
    lat: 6.4213,
    lng: 79.9961,
    description: 'Popular beach for swimming and water sports.',
    estimatedCost: 2000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'brief-garden',
    name: 'Brief Garden',
    district: 'Kalutara',
    category: 'Nature',
    lat: 6.4418,
    lng: 80.0061,
    description: 'Artistic landscaped garden created by Bevis Bawa.',
    estimatedCost: 2000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'kande-viharaya',
    name: 'Kande Viharaya',
    district: 'Kalutara',
    category: 'Religious Sites',
    lat: 6.4639,
    lng: 80.0227,
    description: 'Temple complex with a towering seated Buddha statue.',
    estimatedCost: 1000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },

  {
    placeId: 'temple-of-the-tooth',
    name: 'Temple of the Tooth',
    district: 'Kandy',
    category: 'Religious Sites',
    lat: 7.2936,
    lng: 80.6413,
    description: 'Sacred temple housing the revered tooth relic.',
    estimatedCost: 2500,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'kandy-lake',
    name: 'Kandy Lake',
    district: 'Kandy',
    category: 'Scenic Views',
    lat: 7.2925,
    lng: 80.641,
    description: 'Serene lake with a shaded walking path.',
    estimatedCost: 500,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'peradeniya-botanical-garden',
    name: 'Peradeniya Botanical Gardens',
    district: 'Kandy',
    category: 'Nature',
    lat: 7.2719,
    lng: 80.5967,
    description: 'Botanical gardens famed for orchids and giant trees.',
    estimatedCost: 3000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'udawatta-kele',
    name: 'Udawatta Kele Sanctuary',
    district: 'Kandy',
    category: 'Wildlife',
    lat: 7.2962,
    lng: 80.6437,
    description: 'Forest reserve with walking trails and birdlife.',
    estimatedCost: 1500,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'bahirawakanda-buddha',
    name: 'Bahirawakanda Buddha',
    district: 'Kandy',
    category: 'Scenic Views',
    lat: 7.2903,
    lng: 80.633,
    description: 'Hilltop statue overlooking Kandy city.',
    estimatedCost: 1200,
    createdAt: baseDate,
    updatedAt: baseDate,
  },

  {
    placeId: 'sigiriya-rock-fortress',
    name: 'Sigiriya Rock Fortress',
    district: 'Matale',
    category: 'Historical Sites',
    lat: 7.957,
    lng: 80.76,
    description: 'Ancient rock fortress with frescoes and panoramic views.',
    estimatedCost: 6000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'dambulla-cave-temple',
    name: 'Dambulla Cave Temple',
    district: 'Matale',
    category: 'Religious Sites',
    lat: 7.8567,
    lng: 80.6498,
    description: 'Cave temples with murals and Buddha statues.',
    estimatedCost: 3500,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'pidurangala-rock',
    name: 'Pidurangala Rock',
    district: 'Matale',
    category: 'Hiking',
    lat: 7.9658,
    lng: 80.7591,
    description: 'Hike to a summit with views of Sigiriya.',
    estimatedCost: 2000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'aluvihare-rock-temple',
    name: 'Aluvihare Rock Temple',
    district: 'Matale',
    category: 'Religious Sites',
    lat: 7.4676,
    lng: 80.6221,
    description: 'Historic temple with ancient scriptures and caves.',
    estimatedCost: 1200,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'sembuwatta-lake',
    name: 'Sembuwatta Lake',
    district: 'Matale',
    category: 'Nature',
    lat: 7.4057,
    lng: 80.7021,
    description: 'Man-made lake surrounded by pine forests.',
    estimatedCost: 1800,
    createdAt: baseDate,
    updatedAt: baseDate,
  },

  {
    placeId: 'horton-plains',
    name: 'Horton Plains',
    district: 'Nuwara Eliya',
    category: 'Nature',
    lat: 6.8094,
    lng: 80.8089,
    description: 'Highland plateau with grasslands and wildlife.',
    estimatedCost: 5000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'worlds-end',
    name: "World's End",
    district: 'Nuwara Eliya',
    category: 'Scenic Views',
    lat: 6.8028,
    lng: 80.7951,
    description: 'Dramatic escarpment with sweeping mountain views.',
    estimatedCost: 4000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'gregory-lake',
    name: 'Gregory Lake',
    district: 'Nuwara Eliya',
    category: 'Adventure',
    lat: 6.9682,
    lng: 80.7738,
    description: 'Lake with boating and lakeside recreation.',
    estimatedCost: 2500,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'seetha-amman-temple',
    name: 'Seetha Amman Temple',
    district: 'Nuwara Eliya',
    category: 'Cultural Experiences',
    lat: 6.9508,
    lng: 80.7982,
    description: 'Colorful temple linked to the Ramayana story.',
    estimatedCost: 1000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'hakgala-botanical-garden',
    name: 'Hakgala Botanical Garden',
    district: 'Nuwara Eliya',
    category: 'Nature',
    lat: 6.9277,
    lng: 80.8187,
    description: 'Cool-climate gardens with roses and exotic plants.',
    estimatedCost: 2000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },

  {
    placeId: 'galle-fort',
    name: 'Galle Fort',
    district: 'Galle',
    category: 'Historical Sites',
    lat: 6.026,
    lng: 80.217,
    description: 'UNESCO-listed fort with colonial streets and ramparts.',
    estimatedCost: 2000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'unawatuna-beach',
    name: 'Unawatuna Beach',
    district: 'Galle',
    category: 'Beaches',
    lat: 6.0108,
    lng: 80.2497,
    description: 'Palm-fringed bay with calm water and snorkeling.',
    estimatedCost: 2000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'jungle-beach',
    name: 'Jungle Beach',
    district: 'Galle',
    category: 'Beaches',
    lat: 6.0405,
    lng: 80.2417,
    description: 'Hidden cove reachable by a short forest walk.',
    estimatedCost: 1500,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'japanese-peace-pagoda',
    name: 'Japanese Peace Pagoda',
    district: 'Galle',
    category: 'Religious Sites',
    lat: 6.0434,
    lng: 80.2391,
    description: 'White pagoda with ocean views near Rumassala hill.',
    estimatedCost: 800,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'koggala-lake',
    name: 'Koggala Lake',
    district: 'Galle',
    category: 'Nature',
    lat: 5.9998,
    lng: 80.3295,
    description: 'Large coastal lake with mangroves and islets.',
    estimatedCost: 1800,
    createdAt: baseDate,
    updatedAt: baseDate,
  },

  {
    placeId: 'mirissa-beach',
    name: 'Mirissa Beach',
    district: 'Matara',
    category: 'Beaches',
    lat: 5.9466,
    lng: 80.4587,
    description: 'Popular beach for snorkeling and whale watching.',
    estimatedCost: 3000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'matara-fort',
    name: 'Matara Fort',
    district: 'Matara',
    category: 'Historical Sites',
    lat: 5.9475,
    lng: 80.535,
    description: 'Dutch fort overlooking the Nilwala River.',
    estimatedCost: 900,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'parey-dewa-temple',
    name: 'Parey Dewa Temple',
    district: 'Matara',
    category: 'Religious Sites',
    lat: 5.9499,
    lng: 80.5424,
    description: 'Small island temple reached by a footbridge.',
    estimatedCost: 700,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'polhena-beach',
    name: 'Polhena Beach',
    district: 'Matara',
    category: 'Beaches',
    lat: 5.9389,
    lng: 80.5876,
    description: 'Calm beach protected by a reef, good for swimming.',
    estimatedCost: 1200,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'weherahena-temple',
    name: 'Weherahena Temple',
    district: 'Matara',
    category: 'Cultural Experiences',
    lat: 5.9782,
    lng: 80.5678,
    description: 'Temple famous for its massive seated Buddha statue.',
    estimatedCost: 1000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },

  {
    placeId: 'yala-national-park',
    name: 'Yala National Park',
    district: 'Hambantota',
    category: 'Wildlife',
    lat: 6.3667,
    lng: 81.5167,
    description: 'Safari park known for leopards and elephants.',
    estimatedCost: 8000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'bundala-national-park',
    name: 'Bundala National Park',
    district: 'Hambantota',
    category: 'Wildlife',
    lat: 6.2002,
    lng: 81.2455,
    description: 'Coastal wetland with migratory birds and lagoons.',
    estimatedCost: 6000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'tangalle-beach',
    name: 'Tangalle Beach',
    district: 'Hambantota',
    category: 'Beaches',
    lat: 6.0244,
    lng: 80.7907,
    description: 'Wide sandy beach with quiet bays and coves.',
    estimatedCost: 2000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'ridiyagama-safari-park',
    name: 'Ridiyagama Safari Park',
    district: 'Hambantota',
    category: 'Wildlife',
    lat: 6.2709,
    lng: 80.9403,
    description: 'Open safari park with multiple animal zones.',
    estimatedCost: 4500,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'kalametiya-bird-sanctuary',
    name: 'Kalametiya Bird Sanctuary',
    district: 'Hambantota',
    category: 'Wildlife',
    lat: 6.0909,
    lng: 80.9126,
    description: 'Lagoon sanctuary ideal for bird watching.',
    estimatedCost: 2500,
    createdAt: baseDate,
    updatedAt: baseDate,
  },

  {
    placeId: 'jaffna-fort',
    name: 'Jaffna Fort',
    district: 'Jaffna',
    category: 'Historical Sites',
    lat: 9.6615,
    lng: 80.0092,
    description: 'Historic fort built by the Portuguese and Dutch.',
    estimatedCost: 1200,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'nallur-kandaswamy-temple',
    name: 'Nallur Kandaswamy Temple',
    district: 'Jaffna',
    category: 'Religious Sites',
    lat: 9.6746,
    lng: 80.0297,
    description: 'Major Hindu temple known for festivals and rituals.',
    estimatedCost: 1000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'casuarina-beach',
    name: 'Casuarina Beach',
    district: 'Jaffna',
    category: 'Beaches',
    lat: 9.8149,
    lng: 80.118,
    description: 'Shallow calm waters and casuarina trees.',
    estimatedCost: 1500,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'keerimalai-hot-springs',
    name: 'Keerimalai Hot Springs',
    district: 'Jaffna',
    category: 'Nature',
    lat: 9.7462,
    lng: 79.9983,
    description: 'Natural hot springs next to the coast.',
    estimatedCost: 1200,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'nagadeepa-temple',
    name: 'Nagadeepa Temple',
    district: 'Jaffna',
    category: 'Religious Sites',
    lat: 9.6108,
    lng: 79.7925,
    description: 'Island temple with Buddhist and Hindu significance.',
    estimatedCost: 2200,
    createdAt: baseDate,
    updatedAt: baseDate,
  },

  {
    placeId: 'nilaveli-beach',
    name: 'Nilaveli Beach',
    district: 'Trincomalee',
    category: 'Beaches',
    lat: 8.7073,
    lng: 81.1891,
    description: 'Powdery white sand beach with clear water.',
    estimatedCost: 2000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'pigeon-island',
    name: 'Pigeon Island National Park',
    district: 'Trincomalee',
    category: 'Wildlife',
    lat: 8.7189,
    lng: 81.2525,
    description: 'Marine park with coral reefs and snorkeling.',
    estimatedCost: 5000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'koneswaram-temple',
    name: 'Koneswaram Temple',
    district: 'Trincomalee',
    category: 'Religious Sites',
    lat: 8.5749,
    lng: 81.239,
    description: 'Clifftop Hindu temple with sea views.',
    estimatedCost: 1200,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'marble-beach',
    name: 'Marble Beach',
    district: 'Trincomalee',
    category: 'Beaches',
    lat: 8.5869,
    lng: 81.2154,
    description: 'Quiet beach with calm waters near the harbor.',
    estimatedCost: 1200,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'fort-frederick',
    name: 'Fort Frederick',
    district: 'Trincomalee',
    category: 'Historical Sites',
    lat: 8.5796,
    lng: 81.2437,
    description: 'Colonial fort guarding the Trincomalee harbor.',
    estimatedCost: 1000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },

  {
    placeId: 'batticaloa-lagoon',
    name: 'Batticaloa Lagoon',
    district: 'Batticaloa',
    category: 'Nature',
    lat: 7.7109,
    lng: 81.6923,
    description: 'Lagoon famous for birds and calm evening views.',
    estimatedCost: 1500,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'kallady-bridge',
    name: 'Kallady Bridge',
    district: 'Batticaloa',
    category: 'Scenic Views',
    lat: 7.7367,
    lng: 81.6794,
    description: 'Bridge crossing the lagoon with sunset scenery.',
    estimatedCost: 300,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'pasikudah-beach',
    name: 'Pasikudah Beach',
    district: 'Batticaloa',
    category: 'Beaches',
    lat: 7.9241,
    lng: 81.5622,
    description: 'Shallow bay ideal for swimming and snorkeling.',
    estimatedCost: 2500,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'batticaloa-dutch-fort',
    name: 'Dutch Fort Batticaloa',
    district: 'Batticaloa',
    category: 'Historical Sites',
    lat: 7.7103,
    lng: 81.7011,
    description: 'Seventeenth-century fort near the lagoon.',
    estimatedCost: 800,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'unnichchai-dam',
    name: 'Unnichchai Dam',
    district: 'Batticaloa',
    category: 'Nature',
    lat: 7.5879,
    lng: 81.5599,
    description: 'Reservoir with scenic surroundings and birdlife.',
    estimatedCost: 1200,
    createdAt: baseDate,
    updatedAt: baseDate,
  },

  {
    placeId: 'sri-maha-bodhi',
    name: 'Sri Maha Bodhi',
    district: 'Anuradhapura',
    category: 'Religious Sites',
    lat: 8.3441,
    lng: 80.3967,
    description: 'Sacred Bodhi tree, one of the oldest in the world.',
    estimatedCost: 1500,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'ruwanwelisaya',
    name: 'Ruwanwelisaya',
    district: 'Anuradhapura',
    category: 'Religious Sites',
    lat: 8.3503,
    lng: 80.3964,
    description: 'Iconic stupa with grand white dome.',
    estimatedCost: 1500,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'jetavanaramaya',
    name: 'Jetavanaramaya',
    district: 'Anuradhapura',
    category: 'Historical Sites',
    lat: 8.3462,
    lng: 80.4055,
    description: 'Massive ancient stupa and monastery complex.',
    estimatedCost: 1800,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'isurumuniya',
    name: 'Isurumuniya Temple',
    district: 'Anuradhapura',
    category: 'Cultural Experiences',
    lat: 8.3145,
    lng: 80.4037,
    description: 'Temple known for its stone carvings and pond.',
    estimatedCost: 1200,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'abhayagiri-dagoba',
    name: 'Abhayagiri Dagoba',
    district: 'Anuradhapura',
    category: 'Historical Sites',
    lat: 8.3559,
    lng: 80.4066,
    description: 'Ruins of a vast ancient monastery and stupa.',
    estimatedCost: 1600,
    createdAt: baseDate,
    updatedAt: baseDate,
  },

  {
    placeId: 'polonnaruwa-ancient-city',
    name: 'Polonnaruwa Ancient City',
    district: 'Polonnaruwa',
    category: 'Historical Sites',
    lat: 7.9396,
    lng: 81.0004,
    description: 'UNESCO site with palaces, stupas, and reservoirs.',
    estimatedCost: 5000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'gal-vihara',
    name: 'Gal Vihara',
    district: 'Polonnaruwa',
    category: 'Religious Sites',
    lat: 7.9663,
    lng: 81.0003,
    description: 'Rock-cut Buddha statues from the Polonnaruwa era.',
    estimatedCost: 2500,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'parakrama-samudra',
    name: 'Parakrama Samudra',
    district: 'Polonnaruwa',
    category: 'Scenic Views',
    lat: 7.9287,
    lng: 81.0229,
    description: 'Historic reservoir with expansive water views.',
    estimatedCost: 1200,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'lankatilaka-temple',
    name: 'Lankatilaka Temple',
    district: 'Polonnaruwa',
    category: 'Historical Sites',
    lat: 7.9746,
    lng: 81.0032,
    description: 'Ancient brick temple with massive Buddha statue.',
    estimatedCost: 2000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'rankot-vihara',
    name: 'Rankot Vihara',
    district: 'Polonnaruwa',
    category: 'Religious Sites',
    lat: 7.9678,
    lng: 81.0009,
    description: 'Large stupa modeled after Anuradhapura dagobas.',
    estimatedCost: 2000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },

  {
    placeId: 'nine-arches-bridge',
    name: 'Nine Arches Bridge',
    district: 'Badulla',
    category: 'Scenic Views',
    lat: 6.8721,
    lng: 81.0473,
    description: 'Iconic brick railway bridge near Ella.',
    estimatedCost: 1500,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'ella-rock',
    name: 'Ella Rock',
    district: 'Badulla',
    category: 'Hiking',
    lat: 6.8665,
    lng: 81.059,
    description: 'Popular hike to a viewpoint above Ella.',
    estimatedCost: 2000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'ravana-falls',
    name: 'Ravana Falls',
    district: 'Badulla',
    category: 'Waterfalls',
    lat: 6.8488,
    lng: 81.0478,
    description: 'Famous roadside waterfall near Ella.',
    estimatedCost: 800,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'demodara-loop',
    name: 'Demodara Loop',
    district: 'Badulla',
    category: 'Scenic Views',
    lat: 6.8993,
    lng: 81.0543,
    description: 'Railway loop with a dramatic tunnel curve.',
    estimatedCost: 700,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'liptons-seat',
    name: "Lipton's Seat",
    district: 'Badulla',
    category: 'Scenic Views',
    lat: 6.7041,
    lng: 80.9024,
    description: 'Tea plantation viewpoint with sunrise vistas.',
    estimatedCost: 1800,
    createdAt: baseDate,
    updatedAt: baseDate,
  },

  {
    placeId: 'adams-peak',
    name: "Adam's Peak",
    district: 'Ratnapura',
    category: 'Hiking',
    lat: 6.8096,
    lng: 80.499,
    description: 'Pilgrimage hike to a sacred summit footprint.',
    estimatedCost: 2500,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'sinharaja-forest',
    name: 'Sinharaja Forest Reserve',
    district: 'Ratnapura',
    category: 'Wildlife',
    lat: 6.4062,
    lng: 80.4896,
    description: 'UNESCO rainforest with endemic species.',
    estimatedCost: 5000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'udawalawe-national-park',
    name: 'Udawalawe National Park',
    district: 'Ratnapura',
    category: 'Wildlife',
    lat: 6.476,
    lng: 80.8891,
    description: 'Safari park known for elephants and open plains.',
    estimatedCost: 7000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'bopath-ella',
    name: 'Bopath Ella Falls',
    district: 'Ratnapura',
    category: 'Waterfalls',
    lat: 6.7503,
    lng: 80.365,
    description: 'Waterfall shaped like a Bo leaf during monsoon.',
    estimatedCost: 1200,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'ratnapura-gem-museum',
    name: 'Ratnapura Gem Museum',
    district: 'Ratnapura',
    category: 'Cultural Experiences',
    lat: 6.7056,
    lng: 80.3847,
    description: 'Museum showcasing gemstones and mining heritage.',
    estimatedCost: 1500,
    createdAt: baseDate,
    updatedAt: baseDate,
  },

  {
    placeId: 'kurunegala-lake',
    name: 'Kurunegala Lake',
    district: 'Kurunegala',
    category: 'Scenic Views',
    lat: 7.4885,
    lng: 80.362,
    description: 'City lake with a relaxed evening atmosphere.',
    estimatedCost: 400,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'ethagala-rock',
    name: 'Ethagala Rock',
    district: 'Kurunegala',
    category: 'Scenic Views',
    lat: 7.4863,
    lng: 80.3612,
    description: 'Elephant-shaped rock with panoramic views.',
    estimatedCost: 800,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'ridi-viharaya',
    name: 'Ridi Viharaya',
    district: 'Kurunegala',
    category: 'Religious Sites',
    lat: 7.5197,
    lng: 80.3629,
    description: 'Ancient temple with cave shrines and murals.',
    estimatedCost: 1200,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'yapahuwa-fortress',
    name: 'Yapahuwa Rock Fortress',
    district: 'Kurunegala',
    category: 'Historical Sites',
    lat: 7.7867,
    lng: 80.3145,
    description: 'Ruined fortress with a grand stone staircase.',
    estimatedCost: 2000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'panduwasnuwara',
    name: 'Panduwasnuwara',
    district: 'Kurunegala',
    category: 'Historical Sites',
    lat: 7.7216,
    lng: 80.1812,
    description: 'Ancient city ruins linked to early Sinhalese kings.',
    estimatedCost: 1500,
    createdAt: baseDate,
    updatedAt: baseDate,
  },

  {
    placeId: 'kalpitiya-beach',
    name: 'Kalpitiya Beach',
    district: 'Puttalam',
    category: 'Beaches',
    lat: 8.2333,
    lng: 79.75,
    description: 'Sandy peninsula known for kitesurfing.',
    estimatedCost: 2500,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'wilpattu-national-park',
    name: 'Wilpattu National Park',
    district: 'Puttalam',
    category: 'Wildlife',
    lat: 8.45,
    lng: 80.0,
    description: 'Largest national park with lakes and leopards.',
    estimatedCost: 7000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'munneswaram-temple',
    name: 'Munneswaram Temple',
    district: 'Puttalam',
    category: 'Religious Sites',
    lat: 7.577,
    lng: 79.8079,
    description: 'Ancient Hindu temple complex near Chilaw.',
    estimatedCost: 1000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'kalpitiya-dutch-fort',
    name: 'Dutch Fort Kalpitiya',
    district: 'Puttalam',
    category: 'Historical Sites',
    lat: 8.2327,
    lng: 79.7606,
    description: 'Small coastal fort built by the Dutch.',
    estimatedCost: 800,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'anawilundawa-sanctuary',
    name: 'Anawilundawa Sanctuary',
    district: 'Puttalam',
    category: 'Wildlife',
    lat: 7.6791,
    lng: 79.8218,
    description: 'Ramsar wetland with lakes and bird species.',
    estimatedCost: 2000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },

  {
    placeId: 'arugam-bay',
    name: 'Arugam Bay',
    district: 'Ampara',
    category: 'Beaches',
    lat: 6.8431,
    lng: 81.8359,
    description: 'Famous surf destination with laid-back vibes.',
    estimatedCost: 3000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'lahugala-national-park',
    name: 'Lahugala National Park',
    district: 'Ampara',
    category: 'Wildlife',
    lat: 6.8763,
    lng: 81.6689,
    description: 'Elephant habitat with seasonal reservoirs.',
    estimatedCost: 3500,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'kumana-national-park',
    name: 'Kumana National Park',
    district: 'Ampara',
    category: 'Wildlife',
    lat: 6.5333,
    lng: 81.6667,
    description: 'Bird sanctuary with lagoons and wetlands.',
    estimatedCost: 5000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'magul-maha-viharaya',
    name: 'Magul Maha Viharaya',
    district: 'Ampara',
    category: 'Historical Sites',
    lat: 6.7386,
    lng: 81.7856,
    description: 'Ancient Buddhist ruins near Lahugala.',
    estimatedCost: 1500,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'okanda-beach',
    name: 'Okanda Beach',
    district: 'Ampara',
    category: 'Beaches',
    lat: 6.5702,
    lng: 81.8186,
    description: 'Remote beach at the edge of Kumana forests.',
    estimatedCost: 2000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },

  {
    placeId: 'buduruwagala',
    name: 'Buduruwagala',
    district: 'Monaragala',
    category: 'Historical Sites',
    lat: 6.712,
    lng: 81.0969,
    description: 'Ancient rock carvings with a giant Buddha figure.',
    estimatedCost: 1500,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'maligawila-buddha-statue',
    name: 'Maligawila Buddha Statue',
    district: 'Monaragala',
    category: 'Religious Sites',
    lat: 6.8756,
    lng: 81.3467,
    description: 'Giant standing Buddha statue carved from limestone.',
    estimatedCost: 1500,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'gal-oya-national-park',
    name: 'Gal Oya National Park',
    district: 'Monaragala',
    category: 'Wildlife',
    lat: 7.2433,
    lng: 81.4274,
    description: 'Wildlife park known for elephants and boat safaris.',
    estimatedCost: 6000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'maduru-oya-national-park',
    name: 'Maduru Oya National Park',
    district: 'Monaragala',
    category: 'Wildlife',
    lat: 7.7247,
    lng: 81.1161,
    description: 'Remote park with elephants, birds, and reservoirs.',
    estimatedCost: 6000,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    placeId: 'dambana-vedda-village',
    name: 'Dambana Vedda Village',
    district: 'Monaragala',
    category: 'Cultural Experiences',
    lat: 7.3533,
    lng: 81.1086,
    description: 'Traditional village showcasing indigenous culture.',
    estimatedCost: 2500,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
];

export const seedPlaces = async (): Promise<void> => {
  const uri = process.env.MONGODB_URI || '';
  const dbName = process.env.DB_NAME || 'trip_planner';

  if (!uri) {
    throw new Error('Missing MONGODB_URI environment variable');
  }

  try {
    await mongoose.connect(uri, { dbName });

    const placeIds = places.map((place) => place.placeId);
    const existing = await Place.find({ placeId: { $in: placeIds } })
      .select('placeId')
      .lean();

    const existingIds = new Set(existing.map((place) => place.placeId));
    const newPlaces = places.filter((place) => !existingIds.has(place.placeId));

    if (newPlaces.length === 0) {
      console.log('No new places to insert');
      return;
    }

    await Place.insertMany(newPlaces, { ordered: false });
    console.log(`Inserted ${newPlaces.length} places`);
  } finally {
    await mongoose.disconnect();
  }
};

if (require.main === module) {
  seedPlaces().catch((error) => {
    console.error('Seed failed:', error);
    process.exitCode = 1;
  });
}
